package com.altenheim.kalender.resourceClasses;

public enum ComboBoxCreate 
{
    VEHICLES,
    START,
    DESTINATION,
    RECCURENCEOPTIONS,
    MENUNOTIFICATIONMIN,
    SELECTIONSPECIALFIELD,
    SELECTIONCOURSE,
    SELECTIONSEMESTER,   
    MAILTEMPLATESELECTORTEMPLATE,
    CALENDERNAMES,
    MAILADRESSES
}
